#ifndef MESSAGE_TYPES_H
#define MESSAGE_TYPES_H

// Message type constants
#define MSG_QUERY_AVAILABILITY 1
#define MSG_BOOK_FACILITY 2
#define MSG_CHANGE_BOOKING 3
#define MSG_MONITOR_FACILITY 4
#define MSG_GET_LAST_BOOKING_TIME 5
#define MSG_EXTEND_BOOKING 6
#define MSG_RESPONSE_SUCCESS 100
#define MSG_RESPONSE_ERROR 101

// Network constants
#define TIMEOUT_SECONDS 3
#define MAX_RETRIES 3
#define MAX_BUFFER_SIZE 65507

#endif // MESSAGE_TYPES_H