"""
Message Types Constants
Must match server definitions
"""

# Message type constants
MSG_QUERY_AVAILABILITY = 1
MSG_BOOK_FACILITY = 2
MSG_CHANGE_BOOKING = 3
MSG_MONITOR_FACILITY = 4
MSG_GET_LAST_BOOKING_TIME = 5
MSG_EXTEND_BOOKING = 6
MSG_RESPONSE_SUCCESS = 100
MSG_RESPONSE_ERROR = 101

# Network constants
TIMEOUT_SECONDS = 3
MAX_RETRIES = 3
MAX_BUFFER_SIZE = 65507
